### PR TITLE
Relaunch

### PR DESCRIPTION
**Pull request by steven4714**

### CODE REVIEW

**Comment by schliflo** [comment]
Great work, as always :)
I have some minor nitpicks though:
1. While i like the intersectionObserver approach for lazy loading, there is native support for this via `loading="lazy"` in all browsers except safari (which is ok, as I consider this progressive enhancement). See https://web.dev/browser-level-image-lazy-loading/ or https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading - imho this would be a more performant and less complex solution.
2. We're using PNG for most images right now. This is ok for illustration and graphics, that have complex shadows or gradients. All other graphics would be better in SVG. Pictures like the ones we use on the team page would be best in JPEG.

Have a nice Sunday :)
Cheers!

**Review by schliflo — CHANGES_REQUESTED** [review]
Great work, as always :)
I have some minor nitpicks though:
1. While i like the intersectionObserver approach for lazy loading, there is native support for this via `loading="lazy"` in all browsers except safari (which is ok, as I consider this progressive enhancement). See https://web.dev/browser-level-image-lazy-loading/ or https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading - imho this would be a more performant and less complex solution.
2. We're using PNG for most images right now. This is ok for illustration and graphics, that have complex shadows or gradients. All other graphics would be better in SVG. Pictures like the ones we use on the team page would be best in JPEG.

Have a nice Sunday :)
Cheers!

**Comment by steven4714** [comment]
Thank you :) 

Now using the native lazy loading approach. Also removed the PlaceholderImage component to serve different sizes of the image for mobile. Blurred Preview may come back at some point.

Also converted some Images to jpg and our logo is now svg.

Cheers

**Review by schliflo — APPROVED** [review]
LGTM 👍

**Pull request merged**
